---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: thinkcentre-m80q
description: a custom fedora atomic (kionite) distro for my desktop of choice
base-image: ghcr.io/ublue-os/kionite-main
image-version: 44

platforms:
  - linux/amd64

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo

    install:
      packages:
        - hyfetch
        - fastfetch
        - tailscale
        - gnome-firmware
        - mediawriter
        - cpu-x
        - k3b
        - kate
        - spectacle
        - kcalc
        - kcharselect
        - kdf
        - okular
        - gwenview
        - gnome-disk-utility

    remove:
      packages:
        - firefox
        - firefox-langpacks
        - kde-partitionmanager

  - type: script
    snippets:
      - systemctl enable tailscaled.service
      - dnf5 install -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - dnf5 install -y google-chrome-stable

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system

        remotes:
          - name: flathub
            url: https://dl.flathub.org/repo/flathub.flatpakrepo

          - name: fedora
            url: https://registry.fedoraproject.org
            type: oci
            gpg-verify: false

        install:
          - 
          - com.github.tchx84.Flatseal
          - it.mijorus.gearlever
          - com.usebottles.bottles
          - org.prismlauncher.PrismLauncher
          - com.heroicgameslauncher.hgl

  - type: signing
